plugins {
    alias(libs.plugins.android.application)
}

android {
   	namespace "com.credit.calc"
    compileSdk {
       version = release(36)
    }
    buildToolsVersion  "36.1.0"
    defaultConfig {
        applicationId "com.credit.calc"
        minSdk 28
        targetSdk 36
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

	buildFeatures {
        viewBinding true
    }
}
tasks.register("printCompileClasspath") {
    notCompatibleWithConfigurationCache("Used only for tooling (jdtls classpath generation)")

    doLast {
        println("---START---")
        configurations.debugCompileClasspath.files.each { file ->
            println(file.absolutePath)
        }
        println("---END---")
    }
}


dependencies {
    implementation libs.appcompat
    implementation libs.material
    implementation libs.constraintlayout
    implementation libs.androidx.activity
    // implementation libs.androidx-core
}
